# Welcome to Jekyll!

# Website settings
title: "Feldman Research Lab"
description: "Feldman Research Labs."
keywords: ""
baseurl: "/"
#url: "http://researchlab.tv"
url: "http://127.0.0.1:4000"

# author
author:
  name: 'Alex Feldman'
  first_name: 'Alex'
  last_name: 'Feldman'
  email: 'felday@brandeis.edu'
  github_username: 'aalllxx'
  desc: ''

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# google analytics
ga:
  id: UA-xx


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
